#EpicRageQuit Configuration File.
#Color Codes work with &
#You can use {player} in Broadcast Message and Kick Message as the player name.


# No touchy me config version.
config version: 2

# RageQuit command.
ragequit:
   # Cooldown header
  cooldown:
   # Time in secs. the command will be on cooldown.
    time: 600
    # Use cooldown? true or false
    use: true
 
# Messages Header 
messages:
   # Prefix for messages
   prefix: '&8[&bEpic&fRageQuit&8] &c'
   # Console Deny Message
   console deny: '&cSilly CONSOLE you can not rage.'   
   # No Permission Message
   no permission: '&cSorry you do not have permission.'

   #Default Format Messages (Used when the player has ragequit.default permission)
   default:
     broadcast message: '&f{player} &crage quit.'
     kick message: '&f{player} &cyou rage quit.'
   #Admin Format Messages (Used when the player has ragequit.admin permission)
   admin:
     broadcast message: '&f{player} &crage quit.'
     kick message: '&f{player} &cyou rage quit.'      
   #Moderator Format Messages (Used when the player has ragequit.moderator permission)  
   moderator:
     broadcast message: '&f{player} &crage quit.'
     kick message: '&f{player} &cyou rage quit.'