#EpicRageQuit Configuration File.
#Color Codes work with &
#You can use %player% in Broadcast Message and Kick Message as the player name
#Comments Below show what the different options mean:
#Config Version (DO NOT TOUCH PLUGIN WILL NOT WORK)
#Broadcast Message: Is broadcast when someone ragequits
#Kick Message: Is used as the kick reason when someone uses /ragequit
#Console Deny: Is used if someone trys to use /ragequit in CONSOLE
Config Version: 1
messages:
   Broacast Message: '&f%player% &crage quit.'
   Kick Message: '&f%player% &cyou rage quit.'
   Console Deny: '&cSilly CONSOLE you can not rage.' 