#EpicRageQuit configuration file.
#Color Codes work with &
#You can use {player} in broadcast message and kick message as the player name.

# Please do not change this
config_version: 3

# RageQuit command.
ragequit:
  use_broadcasts: true   
  cooldown:
   # Time in secs. the command will be on cooldown.
    time: 600
    # Use cooldown? true or false
    use: true
 
# Messages Header 
messages:
   # Prefix for messages
   prefix: '&8[&bEpic&fRageQuit&8] &c'
   # Console deny message
   console_deny: '&cSilly CONSOLE you can not rage.'   
   # No permission message
   no_permission: '&cSorry you do not have permission.'
   on_cooldown: '&cSorry that command is on cooldown for {cooldown} seconds.' 

formats:
  default:
    permission: 'epicragequit.default'
    broadcast_msg: '&c{player} rage quit.'
    kick_msg: '&cYou rage quit.'
    priority: 1
  moderator:
    permission: 'epicragequit.moderator'
    broadcast_msg: '&c{player} rage quit.'
    kick_msg: '&cYou rage quit.'  
    priority: 2  
  admin:
    permission: 'epicragequit.admin'
    broadcast_msg: '&c{player} rage quit.'
    kick_msg: '&cYou rage quit.'
    priority: 3    