name: EpicRageQuit
main: me.justbru00.epic.ragequit.v2.main.Main
version: 2.1
description: Adds /ragequit
authors: [JustBru00]
api-version: 1.13

commands:
 ragequit:
  description: Makes you rage quit.   